version: '3.8'
services:
  demo-app:
    build: .
    ports:
      - '8000:8000'
    environment:
      - SERVER_PORT=8000
    restart: unless-stopped
    networks:
      demo-net:
        aliases:
          - demo-app
      home-lab-proxy:

networks:
  demo-net:
  home-lab-proxy:
    external: true
